version: '3.1'

services:

  influx:
    build: ./influxdb
    image: clevertodayinc/influxdb
    volumes:
      - "influx_data:/var/lib/influxdb"
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
    ports:
      - "2003:2003"
    deploy:
      restart_policy:
        condition: on-failure

  elasticsearch:
    image: elasticsearch:2.3
    volumes:
      - "es_data:/usr/share/elasticsearch/data"
    deploy:
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana:4.1.2
    volumes:
      - "grafana_data:/var/lib/grafana"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Gr4f4n4
    depends_on:
      - elasticsearch
    deploy:
      restart_policy:
        condition: on-failure

  kibana:
    image: kibana:5
    environment:
     - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    deploy:
      restart_policy:
        condition: on-failure

  logstash:
    image: logstash:2.3
    command: >
      -e "input { gelf { type => docker port => 12201 } } output { elasticsearch { hosts => 'elasticsearch' }}"
    ports:
      - "12201:12201"
      - "12201:12201/udp"
    depends_on:
      - elasticsearch
    deploy:
      restart_policy:
        condition: on-failure

  sensu-server:
    build: ./sensu
    image: clevertodayinc/sensu
    command: server
    volumes:
      - "sensu_config:/conf.d"
      - "sensu_plugins:/plugins"
    environment:
      - "REDIS_HOST=redis"
      - "INFLUXDB_HOST=influx"
    depends_on:
      - influx
      - redis
    deploy:
      restart_policy:
        condition: on-failure

  sensu-client:
    build: ./sensu
    image: clevertodayinc/sensu
    command: client
    environment:
      - "REDIS_HOST=redis"
    depends_on:
      - redis
    deploy:
      restart_policy:
        condition: on-failure

  sensu-api:
    build: ./sensu
    image: clevertodayinc/sensu
    command: api
    environment:
      - "REDIS_HOST=redis"
    depends_on:
      - redis
    deploy:
      restart_policy:
        condition: on-failure

  uchiwa:
    build: ./uchiwa
    image: clevertodayinc/uchiwa
    environment:
      - "SENSU_HOST=sensu-api"
      - "UCHIWA_USERNAME=uchiwa"
      - "UCHIWA_PASSWORD=S4suk3"
    depends_on:
      - sensu-api
    deploy:
      restart_policy:
        condition: on-failure

  redis:
    image: redis:3
    deploy:
      restart_policy:
        condition: on-failure

  wpscan:
    build: ./wpscan
    image: clevertodayinc/wpscan-server
    deploy:
      restart_policy:
        condition: on-failure

  web:
    build: ./proxy
    image: clevertodayinc/clevermonitoring-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    depends_on:
      - grafana
      - kibana
      - elasticsearch
      - influx
      - uchiwa
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  influx_data:
    driver: local
  es_data:
    driver: local
  grafana_data:
    driver: local
  sensu_config:
    driver: local
  sensu_plugins:
    driver: local
