version: '3.1'

services:

  influx:
    image: influxdb:1.2
    volumes:
      - "influx_data:/var/lib/influxdb"
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
    ports:
      - "2003:2003"

  elasticsearch:
    image: elasticsearch:2.3
    volumes:
     - "es_data:/usr/share/elasticsearch/data"

  grafana:
    image: grafana/grafana:4.1.2
    volumes:
      - "grafana_data:/var/lib/grafana"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Gr4f4n4
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:5
    environment:
     - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:2.3
    command: >
      -e "input { gelf { type => docker port => 12201 } } output { elasticsearch { hosts => 'elasticsearch' }}"
    ports:
      - "12201:12201"
      - "12201:12201/udp"
    depends_on:
      - elasticsearch

  sensu-server:
    build: ./sensu
    command: server
    environment:
      - "REDIS_HOST=redis"
      - "INFLUXDB_HOST=influx"
    depends_on:
      - influx
      - redis

  sensu-api:
    build: ./sensu
    command: api
    environment:
      - "REDIS_HOST=redis"
    depends_on:
      - redis

  uchiwa:
    build: ./uchiwa
    environment:
      - "SENSU_HOST=sensu-api"
      - "UCHIWA_USERNAME=uchiwa"
      - "UCHIWA_PASSWORD=S4suk3"
    depends_on:
      - sensu-api

  redis:
    image: redis:3

  web:
    build: ./proxy
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    depends_on:
      - grafana
      - kibana
      - elasticsearch
      - influx
      - uchiwa

volumes:
  influx_data:
    driver: local
  es_data:
    driver: local
  grafana_data:
    driver: local
